- platform: template
  sensors:
    washingmachine_amps:
      value_template: "{{ states('sensor.slave_telldus_tzwp_102_plug_in_switch_current') }}"
      unit_of_measurement: 'A'
      friendly_name: 'Washing Machine ampère'
    washingmachine_volts:
      value_template: "{{ states('sensor.slave_telldus_tzwp_102_plug_in_switch_voltage') }}"
      unit_of_measurement: 'V'
      friendly_name: 'Washing Machine voltage'
    washingmachine_watts:
      value_template: "{{ states('sensor.slave_washing_machine_power') }}"
      unit_of_measurement: 'W'
      friendly_name: 'Washing Machine current consumption'
    washingmachine_total_kw:
      value_template: "{{ states('sensor.slave_telldus_tzwp_102_plug_in_switch_energy') }}"
      unit_of_measurement: 'kWh'
      friendly_name: 'Washing Machine total consumption'