homeassistant:
  name: !secret name
  allowlist_external_dirs:
    - /config/www/cameras
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml

logger:
  default: info
zone: !include zones.yaml
default_config:

config:
frontend: !include frontend.yaml
map:
lovelace:
  mode: yaml

http: !include http.yaml

history:
logbook:
recorder: !include recorder.yaml
#influxdb: !include influxdb.yaml
tts:
  - platform: google_translate

group: !include groups.yaml
#script: !include scripts.yaml
scene: !include scenes.yaml
scene old: !include_dir_merge_list scenes
hacs:
  token: !secret hacs

automation mine: !include_dir_list automation/
sensor: !include_dir_merge_list sensors/
script: !include_dir_named scripts/
device_tracker: !include_dir_list device_tracker/
binary_sensor: !include_dir_merge_list binary_sensors/
weather: !include_dir_merge_list weather/
input_number: !include_dir_named input_number/
input_boolean: !include_dir_named input_boolean/
input_select: !include_dir_named input_select/
input_datetime: !include_dir_named input_datetime/
input_text: !include_dir_named input_text/
light: !include_dir_merge_list light/
switch: !include_dir_merge_list switch/
camera: !include_dir_list camera/
notify: !include_dir_merge_list notify/
image_processing: !include_dir_list image_processing/

mqtt: !include mqtt.yaml

telegram_bot: !include telegram.yaml

remote_homeassistant: !include remote_ha.yaml
