alias: 'Set dryer machine to running'
trigger:
- platform: numeric_state
  entity_id: sensor.slave_telldus_tzwp_102_plug_in_switch_power_2
  above: '200'
  for:
    minutes: 5
condition: []
action:
- service: input_select.select_option
  data:
    entity_id: input_select.dryer_status
    option: "Running"