initial_state: 'on'
alias: 'Front camera motion off'
trigger:
  - platform: state
    entity_id: input_boolean.front_camera_motion
    to: 'on'
    for: '00:10:00'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.front_camera_motion
