initial_state: 'on'
alias: 'Front camera motion detected'
trigger:
  - platform: state
    entity_id: input_boolean.front_camera_motion
    to: 'on'
action:
  - service: script.turn_on
    entity_id: script.snapshot_front_camera
