initial_state: 'on'
alias: 'Motion start'
trigger:
  - platform: event
    event_type: motion_webhook
    event_data:
      action: "start"
  - platform: event
    event_type: motion_webhook
    event_data:
      action: "unknown"
action:
  - service: notify.logfile
    data:
      message: >
        Motion detection event begins on {{ trigger.event.data.camera }}
  - service: input_boolean.turn_on
    entity_id: input_boolean.front_camera_motion
