initial_state: 'on'
alias: 'Motion hook'
trigger:
  - platform: webhook
    webhook_id: !secret front_motion_webhook
action:
  - service: notify.logfile
    data_template:
      message: >
        Motion detection by {{ trigger.webhook_id }} for {{ trigger.json.action }} on {{ trigger.json.camera }} {{ trigger.data }} / {{ trigger.json }}
  - event: motion_webhook
    event_data_template:
      id: "{{ trigger.webhook_id }}"
      action: "{{ trigger.json.action }}"
      camera: "{{ trigger.json.camera }}"
