alias: 'Stop camera stream'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.stream_camera
    to: 'off'
action:
  - service: media_player.turn_off
    data:
      entity_id: "{{ states('input_select.camera_stream_target') }}"
