alias: 'Set washing machine to running'
trigger:
- platform: numeric_state
  entity_id: sensor.slave_telldus_tzwp_102_plug_in_switch_power
  above: '5'
  for:
    minutes: 10
condition: []
action:
- service: input_select.select_option
  data:
    entity_id: input_select.washingmachine_status
    option: "Running"