- platform: template
  sensors: 
    master_bedroom_motion:
      friendly_name: 'MBR Motion'
      device_class: motion
      value_template: "{{ is_state('sensor.slave_fibaro_system_fgms001_zw5_motion_sensor_burglar_3', '8') }}"

- platform: template
  sensors: 
    kitchen_motion:
      friendly_name: 'Kitchen Motion'
      device_class: motion
      value_template: "{{ is_state('sensor.slave_fibaro_system_fgms001_zw5_motion_sensor_burglar_2', '8') }}"

- platform: template
  sensors: 
    living_room_motion:
      friendly_name: 'Livingroom Motion'
      device_class: motion
      value_template: "{{ is_state('sensor.slave_fibaro_system_fgms001_zw5_motion_sensor_burglar', '8') }}"

- platform: template
  sensors: 
    guest_motion:
      friendly_name: 'Guest motion'
      device_class: motion
      value_template: "{{ is_state('sensor.slave_fibaro_system_fgms001_zw5_motion_sensor_burglar_4', '8') }}"